@url_dev=http://localhost:3000/api/v1

### 1. signup
POST {{url_dev}}/sign-up
Content-Type: application/json
x-api-key: ef5e211693c2f922c30bcbd6e5742d3e

{
  "name": "shop11",
  "email": "shop11@gmail.com",
  "password": "123456"
}